name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t uha26/ci-cd-demo-app .

      - name: Run Container and Test Port
        run: |
          docker run -d -p 5000:5000 --name test-container uha26/ci-cd-demo-app
          sleep 5
          curl --fail http://localhost:5000

      - name: Push Docker Image to Docker Hub
        run: docker push uha26/ci-cd-demo-app

      - name: Cleanup
        run: |
          docker stop test-container
          docker rm test-container
