name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t flask-ci-demo .

      - name: Run Container and Test Port
        run: |
          docker run -d -p 5000:5000 --name test-container flask-ci-demo
          sleep 5
          curl --fail http://localhost:5000
